server:
  port: 8080
  servlet:
    context-path: /daily/


mysql:
  url: jdbc:mysql://localhost:3306
  user: root
  password: 123456


datasource1:
  jdbc-url: jdbc:mysql://localhost:3306/?serverTimezone=GMT%2B8
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver


datasource2:
  jdbc-url: jdbc:mysql://localhost:3306/?serverTimezone=GMT%2B8
  username: root
  password: 123456
  driver-class-name: com.mysql.cj.jdbc.Driver
