server:
  port: 8080
  servlet:
    context-path: /daily/


mysql:
  url: jdbc:mysql://localhost:3306
  user: root
  password: 123456


#显然，spring有一个类用来接受这个spring对象
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
